app:
  version: @project.version@
  name: @project.name@
  description: @project.description@

logging:
  pattern:
    level: ${LOG_FORMAT:${spring.application.name} %clr(%5p) %clr([%X{traceId}/%X{spanId}]){yellow}}
  file:
    path: ${LOGGING_PATH:./var/log/spring}
    name: ${LOGGING_NAME:${logging.file.path}/${spring.application.name}.log}
  logback:
    rollingpolicy:
      max-file-size: ${LOGGING_MAX_SIZE:10MB}
      max-history: ${LOGGING_HISTORY:5}


server:
  port: ${PORT:8080}
  servlet:
    context-path: /certsnatcher-ms

spring:
  cache:
    type: "none"
  main:
    allow-bean-definition-overriding: true
  application:
    name: certsnatcher-ms

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
